variable "vpc-name" {}
variable "igw-name" {}
variable "rt-name2" {}
variable "subnet_name" {}
variable "subnet_name2" {}
variable "sg_name" {}
variable "iam-role-eks" {}
variable "iam-role-node" {}
variable "iam-policy-eks" {}
variable "iam-policy-node" {}
variable "cluster-name" {}
variable "eksnode-group-name" {}